#!/bin/sh

if [ -z "$SUSPEND_MODULE" ] && command_exists hibernate-ram && \
	[ -f "/etc/hibernate/ram.conf" ]; then
	SUSPEND_MODULES="hibernate-script"
	do_suspend()
	{
		hibernate-ram
	}
fi

if [ -z "$HIBERNATE_MODULE" ] && command_exists hibernate && \
	[ -f "/etc/hibernate/disk.conf" ]; then
	HIBERNATE_MODULE="hibernate-script"
	do_hibernate()
	{
		hibernate
	}
fi

if [ -z "$SUSPEND_HYBRID_MODULE" ] && command_exists hibernate && \
	[ -f "/etc/hibernate/both.conf" ]; then
	SUSPEND_HYBRID_MODULE="hibernate-script"
	do_suspend_hybrid()
	{
		hibernate -F"/etc/hibernate/both.conf"
	}
fi

